from __future__ import annotations

import sys
from pathlib import Path


def main() -> int:
    repo_root = Path(__file__).resolve().parent
    vton_root = repo_root / "backend" / "cv" / "vton"
    sys.path.insert(0, str(vton_root))

    try:
        from vton_pipeline import run_pipeline  # pylint: disable=import-outside-toplevel
        from utils.paths import get_vton_paths  # pylint: disable=import-outside-toplevel
    except ModuleNotFoundError as exc:
        print("Pipeline Status: FAILED")
        print(f"Reason: Missing dependency: {exc}.")
        print("Run: powershell -ExecutionPolicy Bypass -File backend/cv/vton/scripts/setup_vton_env.ps1")
        return 1

    paths = get_vton_paths()
    person = paths.samples / "person.jpg"
    garment = paths.samples / "garment.jpg"
    if not person.exists() or not garment.exists():
        print("Pipeline Status: FAILED")
        print(f"Reason: Missing sample files. Expected {person} and {garment}")
        return 1

    report = run_pipeline(person, garment, debug=False)
    print(f"Pipeline Status: {report.status}")
    if report.status != "SUCCESS":
        print(f"Reason: {report.reason}")
        return 1

    print("Models Loaded:", ", ".join(report.models_loaded))
    print("Runtime Device:", report.device)
    print(f"Inference Time: {report.runtime_seconds:.2f}s")
    print("Output Resolution: generated by CP-VTON+ (expected 192x256)")
    print("Result:", report.outputs.get("result", "N/A"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
